input:
  filename: "data/fake_data.tsv"
  format: "tsv"
  sample_rows: true
  metadata: true
  metadata_fname: "data/fake_data_meta.tsv"
  max_obs: 50

methods:
  - flashweave
  - spieceasi
  - phyloseq
  - fastspar

fastspar_configs:
  output_dir: "data/fastspar_results/"
  config1:
    iterations: 50
    exclude_iterations: 10
    threshold: 0.2
    network_base: "correlations"

flashweave_configs:
  output_dir: "data/flashweave_results/"
  config1:
    sensitive:     true
    heterogeneous: false

spieceasi_configs:
  output_dir: "data/spieceasi_results/"
  config1_glasso:
    method: "glasso"
    pulsar.select: true
    sel.criterion: "bstars"
    verbose: true

phyloseq_configs:
  output_dir: "data/phyloseq_results/"
  config1_jaccard:
    distance: "binomial"
    max.dist: 0.9
