input:
  filename: "amplicon_occurences_proper.tsv"
  otu_seqs_filename: "db_w5_seqs.fasta"
  format: "tsv"
  sample_rows: false
  metadata: true
  metadata_fname: "amplicon_station_metadata.tsv"
  min_tot_abundance: 1000

fastspar_configs:
  output_dir: "data/fastspar_results/"
  config1:
    iterations: 50
    exclude_iterations: 10
    threshold: 0.2
    network_base: "correlations"

flashweave_configs:
  output_dir: "data/flashweave_results/"
  config1:
    sensitive:     true
    heterogeneous: false

spieceasi_configs:
  output_dir: "data/spieceasi_results/"
  config1_glasso:
    method: "glasso"
    pulsar.select: true
    sel.criterion: "bstars"
    verbose: true

phyloseq_configs:
  output_dir: "data/phyloseq_results/"
  config1_jaccard:
    method: "jaccard"
