input:
  filename: "full_amplicon_occurences.tsv"
  otu_seqs_filename: "db_w5_seqs.fasta"
  format: "tsv"
  sample_rows: true
  metadata: false
  metadata_fname: "amplicon_station_metadata.tsv"
  min_tot_abundance: 1000

fastspar_configs:
  output_dir: "data/fastspar_results/"
  config1:
    iterations: 50
    exclude_iterations: 10
    threshold: 0.2
    network_base: "correlations"

flashweave_configs:
  output_dir: "data/flashweave_results/"
  config1:
    sensitive:     true
    heterogeneous: false
    min_weight: 0.3

spieceasi_configs:
  output_dir: "data/spieceasi_results/"
  config1_glasso:
    method: "glasso"
    pulsar.select: true
    sel.criterion: "bstars"
    verbose: true

phyloseq_configs:
  output_dir: "data/phyloseq_results/"
  config1_jaccard:
    method: "jaccard"
    max.dist: 0.6
    min.weight: 0.1
  config2_canberra:
    method: "canberra"
    max.dist: 0.6
    min.weight: 0.1

visualization:
  max_nodes: 50

consensus_network:
  min_programs: 2
